// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcvHkLEXpdCEk0rFdHKJT5_N0AIiJlO5o',
    appId: '1:721244003399:web:50f052d2ee926c52e6a562',
    messagingSenderId: '721244003399',
    projectId: 'cheyyan-3dfb8',
    authDomain: 'cheyyan-3dfb8.firebaseapp.com',
    databaseURL: 'https://cheyyan-3dfb8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cheyyan-3dfb8.appspot.com',
    measurementId: 'G-L2Q45C64TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQKXHX8ioHHyKUWRpY_vz67nWYPUT4iJs',
    appId: '1:721244003399:android:de4fbca830457b31e6a562',
    messagingSenderId: '721244003399',
    projectId: 'cheyyan-3dfb8',
    databaseURL: 'https://cheyyan-3dfb8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cheyyan-3dfb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkBv0iXhpsj8sbk50Wp9_5_ZmXWpBOFGo',
    appId: '1:721244003399:ios:874d79de281651a9e6a562',
    messagingSenderId: '721244003399',
    projectId: 'cheyyan-3dfb8',
    databaseURL: 'https://cheyyan-3dfb8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cheyyan-3dfb8.appspot.com',
    androidClientId: '721244003399-j4vkf0s4e0kig1e8h7aqdjk017qavjut.apps.googleusercontent.com',
    iosBundleId: 'com.example.cheyyan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkBv0iXhpsj8sbk50Wp9_5_ZmXWpBOFGo',
    appId: '1:721244003399:ios:42f72882095736a7e6a562',
    messagingSenderId: '721244003399',
    projectId: 'cheyyan-3dfb8',
    databaseURL: 'https://cheyyan-3dfb8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cheyyan-3dfb8.appspot.com',
    androidClientId: '721244003399-j4vkf0s4e0kig1e8h7aqdjk017qavjut.apps.googleusercontent.com',
    iosBundleId: 'com.example.cheyyan.RunnerTests',
  );
}
